name: 'Run Swift Tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_ENABLE_LOGGING : "true"
  AWS_LOG_LEVEL: "trace"

jobs:
  swift-tests:
    name: 'Swift Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - swift:5.7.2
    services:
      localstack:
        image: localstack/localstack
    container:
      image: ${{ matrix.image }}
      env:
        LOCALSTACK_ENDPOINT : "http://localstack:4566"
     # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Resource Prefix
        # set AWS_TEST_RESOURCE_PREFIX environment variable to a random series of 8 letters
        run: |
          echo AWS_TEST_RESOURCE_PREFIX=$(cat /dev/urandom | tr -dc 'a-z' | head -c 8) >> $GITHUB_ENV
      - name: Test
        run: |
          swift test --sanitize=thread